title: "深夜孤宅 - 恐怖密室逃脫"
description: "一款使用 HTML、CSS 和 JavaScript 製作的網頁恐怖密室逃脫遊戲"
baseurl: ""
url: ""

# GitHub Pages 設定
plugins:
  - jekyll-relative-links

# 檔案處理
include:
  - "*.html"
  - "*.css"
  - "*.js"
  - "assets/**"

exclude:
  - README.md
  - "*.md"

# MIME 類型設定
defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false
